"""Convert between `.niva` flows and standalone PyQGIS scripts.

``export_script`` turns a `.niva` flow into a runnable, standalone PyQGIS `.py`:
each algorithm stage becomes a ``processing.run(...)`` call, with the layer piped
from one step into the next and a ``save`` directing the preceding step's OUTPUT to
its destination. This is niva's *eject* path — a non-programmer prototypes in niva,
then exports real PyQGIS to learn from, customise, or hand to a developer.

``import_script`` reverses the export: a script that is a **linear sequence of
``processing.run('alg', {...})`` calls** maps each call back to a ``run`` stage.

ROUND-TRIP IS LIMITED BY DESIGN. niva is a linear pipeline; Python is
Turing-complete. Only niva-generated (or niva-shaped) scripts re-import. Anything
``import_script`` cannot map (loops, conditionals, custom functions, non-processing
API calls, non-literal params) is reported in the returned warnings — never
silently dropped.
"""

from __future__ import annotations

import ast

from .engine.connections import is_connection_ref
from .engine.engine import _scalar
from .grammar import Call, Flow, parse
from .registry import bind, core_registry
from .values import Distance


# --- export: .niva -> .py ----------------------------------------------------

_HEADER = """\
# =============================================================================
# Generated by niva {version} from {source}.
#
# This is a standalone PyQGIS script — run it with QGIS's own Python:
#     <qgis_python> {out_name}
# (or paste the body into the QGIS Python console, which is already initialised).
#
# RE-IMPORT NOTE: `niva import` can read this script back into a .niva flow ONLY
# because niva generated it as a linear sequence of processing.run(...) calls.
# Arbitrary PyQGIS scripts CANNOT be imported — niva is a linear pipeline and
# Python is not. If you edit this file, keep it a flat list of processing.run
# calls for it to remain importable.
# =============================================================================

import sys

from qgis.core import QgsApplication

# Initialise a standalone QGIS only if we are not already inside one (e.g. the
# QGIS Python console, where processing is ready to use).
_OWN_APP = QgsApplication.instance() is None
if _OWN_APP:
    QgsApplication.setPrefixPath(sys.prefix, True)
    _APP = QgsApplication([], False)
    _APP.initQgis()
    from qgis.analysis import QgsNativeAlgorithms
    import processing
    from processing.core.Processing import Processing
    Processing.initialize()
    # The native (C++) algorithms are not auto-registered in a standalone app;
    # keep the provider reference alive so it is not garbage-collected mid-run.
    _PROVIDER = QgsNativeAlgorithms(QgsApplication.processingRegistry())
    QgsApplication.processingRegistry().addProvider(_PROVIDER)
else:
    import processing


def main():
"""

_FOOTER = """\

    return {last}


if __name__ == "__main__":
    result = main()
    print("done:", result)
    if _OWN_APP:
        QgsApplication.exitQgis()
        # Hard exit avoids a segfault during interpreter teardown of a standalone
        # QgsApplication (see niva's PyQGIS standalone-init notes).
        import os
        os._exit(0)
"""


class _Raw:
    """A value rendered verbatim in a params dict (a variable name), not repr'd."""

    __slots__ = ("text",)

    def __init__(self, text: str):
        self.text = text


def _lit(value) -> str:
    """Render a single param value as Python source."""
    if isinstance(value, _Raw):
        return value.text
    if isinstance(value, Distance):
        return repr(value.value)  # unit resolved at run time; see the trailing note
    if isinstance(value, bool):
        return "True" if value else "False"
    return repr(value)


def _render_params(params: dict) -> str:
    return ", ".join(f"{k!r}: {_lit(v)}" for k, v in params.items())


def export_script(
    text: str,
    *,
    source_name: str = "<inline>",
    out_name: str = "out.py",
    file: str | None = None,
    version: str | None = None,
) -> str:
    """Transpile `.niva` source to a standalone PyQGIS script (returns the source)."""
    if version is None:
        from . import __version__ as version
    program = parse(text, file=file)
    registry = core_registry()

    body: list[str] = []
    last_var = "None"
    counter = [0]  # step variable counter — shared across every flow in the file
    for item in program:
        if isinstance(item, Call):
            body.append(
                f"    # call {item.target} — not followed by export; "
                f"export that file separately"
            )
            continue
        if isinstance(item, Flow):
            flow_lines, flow_last = _export_flow(item, registry, counter)
            body.extend(flow_lines)
            if flow_last != "None":
                last_var = flow_last

    indented = "\n".join(body) if body else "    pass"
    header = _HEADER.format(version=version, source=source_name, out_name=out_name)
    return header + indented + _FOOTER.format(last=last_var)


def _export_flow(flow: Flow, registry, counter) -> tuple[list[str], str]:
    lines: list[str] = []
    current = None  # _Raw(var) for a piped layer, or a path string for a load
    last_var = "None"
    stages = flow.stages
    i = 0
    while i < len(stages):
        st = stages[i]
        verb = st.verb
        lines.append(f"    # niva: {st.raw}")

        if verb == "load":
            current = st.args[0].split("|", 1)[0] if st.args else None
            lines.append(f"    #   load source: {current!r}")
            i += 1
            continue
        if verb == "save":
            # A standalone save (no preceding algorithm wrote to it). Rare; note it.
            dest = st.args[0] if st.args else "?"
            if st.args and is_connection_ref(st.args[0]):
                lines.append(
                    f"    #   save -> {dest!r} "
                    "(database write — no processing.run equivalent)"
                )
            else:
                lines.append(
                    f"    #   save -> {dest!r} (no transform stage precedes this save)"
                )
            i += 1
            continue
        if verb in ("assess", "metadata", "sql"):
            lines.append(f"    #   ({verb}) has no processing.run equivalent — skipped")
            i += 1
            continue

        # --- an algorithm stage: curated verb or the `run` escape hatch ---
        # Look ahead for a following file `save` to use as this step's OUTPUT. A
        # `save @conn` (database write) has no processing.run OUTPUT equivalent, so we
        # leave it for the standalone-save branch to annotate rather than emit a
        # bogus `OUTPUT='@conn.table'`.
        save_dest = None
        nxt = stages[i + 1] if i + 1 < len(stages) else None
        if (
            nxt
            and nxt.verb == "save"
            and nxt.args
            and not is_connection_ref(nxt.args[0])
        ):
            save_dest = nxt.args[0].split("|", 1)[0]

        try:
            algorithm, params, input_param, output_param, is_curated = _bind_stage(
                st, registry
            )
        except Exception as exc:  # unknown verb / bad bind — emit a comment, keep going
            lines.append(f"    #   could not export this stage: {exc}")
            i += 1
            continue

        full = dict(params)
        # Curated verbs never carry INPUT/OUTPUT in params, so the backend always
        # injects them — mirror that. The `run` escape hatch passes params verbatim:
        # only inject INPUT/OUTPUT when the user did NOT specify them (matches
        # run_raw), so an explicit `OUTPUT=/tmp/x.vrt` survives export.
        if is_curated:
            if current is not None:
                full[input_param] = current
            full[output_param] = save_dest if save_dest else "TEMPORARY_OUTPUT"
        else:
            if current is not None and input_param not in full:
                full[input_param] = current
            if output_param not in full:
                full[output_param] = save_dest if save_dest else "TEMPORARY_OUTPUT"
            elif save_dest:
                full[output_param] = save_dest

        units = [
            f"{v.value}{v.unit}"
            for v in params.values()
            if isinstance(v, Distance) and v.unit
        ]
        counter[0] += 1
        var = f"step{counter[0]}"
        note = (
            (
                "  # " + ", ".join(units) + " — niva resolves the unit against the "
                "input CRS at run time"
            )
            if units
            else ""
        )
        lines.append(
            f"    {var} = processing.run({algorithm!r}, "
            f"{{{_render_params(full)}}})[{output_param!r}]{note}"
        )
        current = _Raw(var)
        last_var = var
        i += 2 if save_dest else 1

    return lines, last_var


def _bind_stage(stage, registry):
    """Return (algorithm, params, input_param, output_param, is_curated). For the
    `run` escape hatch, params are the user's verbatim options (INPUT/OUTPUT may be
    present); for a curated verb they're the binder's resolved params (never)."""
    if stage.verb == "run":
        algorithm = stage.args[0]
        params = {k: _scalar(v) for k, v in stage.options.items()}
        return algorithm, params, "INPUT", "OUTPUT", False
    alias = registry.get(stage.verb)
    if alias is None:
        raise ValueError(f"unknown verb `{stage.verb}`")
    op = bind(stage, alias)
    return op.algorithm, dict(op.params), op.input_param, op.output_param, True


# --- import: .py -> .niva ----------------------------------------------------


def import_script(py_text: str) -> tuple[str, list[str]]:
    """Reverse ``export_script``: parse a linear ``processing.run`` script into a
    `.niva` flow. Returns ``(niva_source, warnings)``. ``warnings`` lists every
    statement that could not be mapped (so nothing is silently lost)."""
    try:
        tree = ast.parse(py_text)
    except SyntaxError as exc:
        return "", [f"not valid Python: {exc}"]

    statements = list(tree.body)
    # The export wraps steps in `def main():` — descend into it if present.
    for node in statements:
        if isinstance(node, ast.FunctionDef) and node.name == "main":
            statements = node.body
            break

    lines: list[str] = []
    warnings: list[str] = []
    prev_var: str | None = None

    for node in statements:
        call, target = _extract_run_call(node)
        if call is None:
            _note_unsupported(node, warnings)
            continue
        parsed = _parse_run_call(call)
        if parsed is None:
            warnings.append(
                f"line {node.lineno}: processing.run with non-literal "
                f"algorithm/params — cannot import"
            )
            continue
        algorithm, items = parsed

        opts: list[str] = []
        for key, value in items:
            if key == "OUTPUT" and value == "TEMPORARY_OUTPUT":
                continue  # niva supplies a temp sink
            if key == "INPUT" and isinstance(value, _Raw) and value.text == prev_var:
                continue  # this is the pipe — niva threads it implicitly
            if isinstance(value, _Raw):
                warnings.append(
                    f"line {node.lineno}: {key} references the variable "
                    f"`{value.text}` — emitted as-is; check the wiring"
                )
                opts.append(f"{key}={value.text}")
                continue
            # An explicit literal INPUT/OUTPUT is kept on the `run` line verbatim —
            # faithful for any source (a single file, a glob, a multilayer list),
            # which a `load` stage could not represent.
            opts.append(f"{key}={_niva_value(value)}")

        lines.append(
            f"run {algorithm} " + " ".join(opts) if opts else f"run {algorithm}"
        )
        prev_var = target

    return "\n".join(lines) + ("\n" if lines else ""), warnings


def _extract_run_call(node):
    """If ``node`` is a processing.run(...) call (optionally assigned/subscripted),
    return (Call, assigned_var_name | None); else (None, None)."""
    target = None
    value = None
    if (
        isinstance(node, ast.Assign)
        and len(node.targets) == 1
        and isinstance(node.targets[0], ast.Name)
    ):
        target = node.targets[0].id
        value = node.value
    elif isinstance(node, ast.Expr):
        value = node.value
    else:
        return None, None

    # peel a trailing subscript: processing.run(...)['OUTPUT']
    if isinstance(value, ast.Subscript):
        value = value.value
    if isinstance(value, ast.Call) and _is_processing_run(value.func):
        return value, target
    return None, None


def _is_processing_run(func) -> bool:
    return (
        isinstance(func, ast.Attribute)
        and func.attr == "run"
        and isinstance(func.value, ast.Name)
        and func.value.id == "processing"
    )


def _parse_run_call(call):
    """Return (algorithm:str, [(key, value), …]) or None if not literal-enough.
    Values are Python literals, or ``_Raw(name)`` for a variable reference."""
    if len(call.args) < 2:
        return None
    alg_node, params_node = call.args[0], call.args[1]
    if not (isinstance(alg_node, ast.Constant) and isinstance(alg_node.value, str)):
        return None
    if not isinstance(params_node, ast.Dict):
        return None
    items = []
    for k, v in zip(params_node.keys, params_node.values):
        if not (isinstance(k, ast.Constant) and isinstance(k.value, str)):
            return None
        items.append((k.value, _literal_or_name(v)))
    return alg_node.value, items


def _literal_or_name(node):
    if isinstance(node, ast.Constant):
        return node.value
    if isinstance(node, ast.Name):
        return _Raw(node.id)
    # a subscript like other['OUTPUT'] -> treat as a variable reference
    if isinstance(node, ast.Subscript) and isinstance(node.value, ast.Name):
        return _Raw(node.value.id)
    try:
        return ast.literal_eval(node)
    except (ValueError, SyntaxError):
        return _Raw("<expr>")


def _niva_value(value) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    text = str(value)
    if text == "" or any(c in text for c in ' \t"|'):
        return '"' + text.replace('"', '\\"') + '"'
    return text


def _note_unsupported(node, warnings: list[str]) -> None:
    # Imports, the QGIS-init boilerplate, return/print, and `def main` wrapper are
    # expected scaffolding — don't warn about those. Flag anything that looks like
    # real work we couldn't map.
    if isinstance(
        node,
        (ast.Import, ast.ImportFrom, ast.Return, ast.Pass, ast.FunctionDef, ast.If),
    ):
        return
    if isinstance(
        node, (ast.For, ast.While, ast.With, ast.Try, ast.AsyncFor, ast.AsyncWith)
    ):
        kind = type(node).__name__.replace("Async", "async ").lower()
        warnings.append(
            f"line {node.lineno}: `{kind}` block cannot import — niva is a "
            f"linear pipeline (no loops/conditionals/context managers)"
        )
        return
    if isinstance(node, ast.Expr) and isinstance(node.value, ast.Call):
        warnings.append(
            f"line {node.lineno}: unsupported call — only "
            f"processing.run(...) statements import"
        )
    elif isinstance(node, ast.Assign):
        warnings.append(
            f"line {node.lineno}: unsupported assignment — only "
            f"processing.run(...) statements import"
        )
